import Head from "next/head";
import styles from "@/styles/home.module.css";

import { createEvent, getEvents } from "../api/event";
import { useState, useEffect, useRef } from "react";
import os from "os";

const json2csv = (json) => {
    const fields = Object.keys(json[0]);
    const csv = json.map((row) => fields.map((i) => row[i]).join(","));
    csv.unshift(fields.join(","));
    return csv.join(os.EOL);
};

const Home = () => {
    const [download, setDownload] = useState([]);
    const downloadLink = useRef();

    const downloadMyCollection = async () => {
        const events = await getEvents();
        console.log(events);
        setDownload(json2csv(events.data.map((event) => event.data)));
    };

    useEffect(() => {
        if (download.length > 0) {
            downloadLink?.current?.click();
            setDownload([]);
        }
    }, [download]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>
                    <button
                        style={{
                            width: "160px",
                            height: "40px",
                            margin: "10px",
                        }}
                        onClick={() =>
                            createEvent({
                                name: "test event 2",
                                description: "test description 2",
                            })
                        }
                    >
                        Create Test Event
                    </button>
                    <button
                        style={{
                            width: "160px",
                            height: "40px",
                            margin: "10px",
                        }}
                        className="downloadButton"
                        onClick={downloadMyCollection}
                    >
                        Download Events
                    </button>
                    <a
                        href={`data:text/csv;charset=utf-8,${encodeURIComponent(
                            download
                        )}`}
                        download="events.csv"
                        hidden={true}
                        ref={downloadLink}
                    ></a>
                </div>
            </main>
        </>
    );
};

export default Home;
