import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import os from "os";
import { createEvent, getEvents } from "@/api/event";
import { event } from "@/tests/mock";
import { type Event } from "@/types";
import styles from "@/styles/home.module.css";

const events2csv = (events: Event[]): string => {
    const fields = Object.keys(events[0]);
    const csv = events.map((event) => Object.values(event).join(","));
    csv.unshift(fields.join(","));
    return csv.join(os.EOL);
};

const Home = () => {
    const [download, setDownload] = useState("");
    const downloadLink = useRef<HTMLAnchorElement>(null);

    const downloadMyCollection = async () => {
        const { data: eventData } = await getEvents();
        const events = eventData.map((event) => event.data);
        setDownload(events2csv(events));
    };

    useEffect(() => {
        if (download.length > 0) {
            downloadLink.current?.click();
            setDownload("");
        }
    }, [download]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>
                    <button
                        style={{
                            width: "160px",
                            height: "40px",
                            margin: "10px",
                        }}
                        onClick={() => createEvent(event)}
                    >
                        Create Test Event
                    </button>
                    <button
                        style={{
                            width: "160px",
                            height: "40px",
                            margin: "10px",
                        }}
                        className="downloadButton"
                        onClick={downloadMyCollection}
                    >
                        Download Events
                    </button>
                    <a
                        href={`data:text/csv;charset=utf-8,${encodeURIComponent(
                            download
                        )}`}
                        download="events.csv"
                        hidden={true}
                        ref={downloadLink}
                    ></a>
                </div>
            </main>
        </>
    );
};

export default Home;
